const order_info_schema ={
  "type": "object",
  "properties": {
      "order": {
          "type": "object",
          "properties": {
              "order_id": {"type": "string"},
              "invoice_no": {"type": "string"},
              "invoice_prefix": {"type": "string"},
              "store_id": {"type": "string"},
              "store_name": {"type": "string"},
              "store_url": {"type": "string"},
              "customer_id": {"type": "string"},
              "firstname": {"type": "string"},
              "lastname": {"type": "string"},
              "email": {"type": "string"},
              "telephone": {"type": "string"},
              "custom_field": {"type": "null"},
              "payment_firstname": {"type": "string"},
              "payment_lastname": {"type": "string"},
              "payment_company": {"type": "string"},
              "payment_address_1": {"type": "string"},
              "payment_address_2": {"type": "string"},
              "payment_postcode": {"type": "string"},
              "payment_city": {"type": "string"},
              "payment_zone_id": {"type": "string"},
              "payment_zone": {"type": "string"},
              "payment_zone_code": {"type": "string"},
              "payment_country_id": {"type": "string"},
              "payment_country": {"type": "string"},
              "payment_iso_code_2": {"type": "string"},
              "payment_iso_code_3": {"type": "string"},
              "payment_address_format": {"type": "string"},
              "payment_custom_field": {"type": "array"},
              "payment_method": {"type": "string"},
              "payment_code": {"type": "string"},
              "shipping_firstname": {"type": "string"},
              "shipping_lastname": {"type": "string"},
              "shipping_company": {"type": "string"},
              "shipping_address_1": {"type": "string"},
              "shipping_address_2": {"type": "string"},
              "shipping_postcode": {"type": "string"},
              "shipping_city": {"type": "string"},
              "shipping_zone_id": {"type": "string"},
              "shipping_zone": {"type": "string"},
              "shipping_zone_code": {"type": "string"},
              "shipping_country_id": {"type": "string"},
              "shipping_country": {"type": "string"},
              "shipping_iso_code_2": {"type": "string"},
              "shipping_iso_code_3": {"type": "string"},
              "shipping_address_format": {"type": "string"},
              "shipping_custom_field": {"type": "array"},
              "shipping_method": {"type": "string"},
              "shipping_code": {"type": "string"},
              "comment": {"type": "string"},
              "total": {"type": "string"},
              "order_status_id": {"type": "string"},
              "order_status": {"type": "string"},
              "affiliate_id": {"type": "string"},
              "commission": {"type": "string"},
              "language_id": {"type": "string"},
              "language_code": {"type": "string"},
              "currency_id": {"type": "string"},
              "currency_code": {"type": "string"},
              "currency_value": {"type": "string"},
              "ip": {"type": "string"},
              "forwarded_ip": {"type": "string"},
              "user_agent": {"type": "string"},
              "accept_language": {"type": "string"},
              "date_added": {"type": "string"},
              "date_modified": {"type": "string"}
          },
          "additionalProperties": false,
          "required": [
              "order_id",
              "invoice_no",
              "invoice_prefix",
              "store_id",
              "store_name",
              "store_url",
              "customer_id",
              "firstname",
              "lastname",
              "email",
              "telephone",
              "payment_firstname",
              "payment_lastname",
              "payment_company",
              "payment_address_1",
              "payment_address_2",
              "payment_postcode",
              "payment_city",
              "payment_zone_id",
              "payment_zone",
              "payment_zone_code",
              "payment_country_id",
              "payment_country",
              "payment_iso_code_2",
              "payment_iso_code_3",
              "payment_address_format",
              "payment_custom_field",
              "payment_method",
              "payment_code",
              "shipping_firstname",
              "shipping_lastname",
              "shipping_company",
              "shipping_address_1",
              "shipping_address_2",
              "shipping_postcode",
              "shipping_city",
              "shipping_zone_id",
              "shipping_zone",
              "shipping_zone_code",
              "shipping_country_id",
              "shipping_country",
              "shipping_iso_code_2",
              "shipping_iso_code_3",
              "shipping_address_format",
              "shipping_custom_field",
              "shipping_method",
              "shipping_code",
              "comment",
              "total",
              "order_status_id",
              "order_status",
              "affiliate_id",
              "commission",
              "language_id",
              "language_code",
              "currency_id",
              "currency_code",
              "currency_value",
              "ip",
              "forwarded_ip",
              "user_agent",
              "accept_language",
              "date_added",
              "date_modified"
          ]
      },
      "success": {"type": "string"}
  },
  "additionalProperties": false,
  "required": ["order", "success"]
}

module.exports = {order_info_schema}